---

apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: bionic-demo
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30001 #port exposed on localhost
  selector:
    app: registry
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: bionic-demo
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - image: pstemberbionic/registry:1.0.0
        name: registry
        ports:
        - containerPort: 8080
        resources: {}
        env: 
          - name: "DOCKER"
            value: "1"

      restartPolicy: Always