---

apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: bionic-demo
spec:
  ports:
  - name: "9091"
    port: 9091
    targetPort: 8080
  selector:
    app: users
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: bionic-demo
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - image: pstemberbionic/users:1.0.0
        name: users
        ports:
        - containerPort: 8080
        resources: {}
        env: 
          - name: "DOCKER"
            value: "1"

      restartPolicy: Always